### ISSUE TITLE
extent doesn't validate scalar numeric inputs

### ISSUE THREAD

**Issue by mdsumner** [mdsumner/raster-rforge#2]
yikes!

```R
extent(145, 146, -44, -45)

## still no error
extent(extent(145, 146, -44, -45))
extent(c(145, 146), c(-44, -45))
```

**Comment by mdsumner** [comment]
Fixed in https://github.com/rforge/raster/commit/4d98d1ceecd482ffc04f75da4fce994ab13eefaa

**Comment by Robinlovelace** [comment]
Great to see development on *raster* underway!

**Comment by mdsumner** [comment]
IKR, I'm hoping to get these summarized and reviewed before a CRAN release, though I'm stuck with a compilation problem atm ...
